version: "3"
services:
  app:
    image: tdp
    env_file:
    - ./server/.env
    ports:
    - "9000:9000"
    - "9001:9001"
    depends_on:
    - db
    restart: always
  db:
    image: mysql
    env_file:
    - ./.env
    ports:
    - "3306:3306"
    volumes:
    - mysqldata:/var/lib/mysql
    command: --authentication_policy=mysql_native_password
    restart: on-failure
volumes:
  mysqldata:
    external: true